############################################################
# mysql database
############################################################
spring:
  datasource:
    url: jdbc:mysql://*******:*******/marine_species?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: *******
    password: *******
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime=120000

